book/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('book_citations/', views.BookCitationsView.as_view(), name='book_citations'),
    path('book_search/', views.SearchBookView.as_view(), name='search_book'),
    path('book_detail/<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('book/', views.BookListView.as_view(), name='book_user'),
    path('book_update/<int:id>/', views.UpdateBookView.as_view(), name='update_book'),
    path('book_create/', views.CreateBookView.as_view(), name='create_book'),
    path('book_delete/<int:id>/', views.DeleteBookView.as_view(), name='delete_book'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
    path('', include('myShop.urls')),
    path('', include('accounts.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100, verbose_name='Укажите названия книги')
    description = models.TextField(verbose_name='Укажите описания книги')
    image = models.ImageField(upload_to='imgBook/', verbose_name='Загрузите картинку книги')
    created_date = models.PositiveIntegerField(verbose_name='Укажите дату выхода книги', null=True)
    creat_at = models.DateTimeField(auto_now_add=True)
    viki_bok = models.URLField(verbose_name='Укажите ссылку на википедию', null=True)
    book_files = models.FileField(upload_to='files/', verbose_name='Загрузите файл книги', null=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name='Книга и ее описание'
        verbose_name_plural = 'Книги и их описание'

book/forms.py
from django import forms
from book.models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__" 

book/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from . import models, forms


class BookCitationsView(View):
    def get(self, request):
        return HttpResponse('«Вы никогда не переплывете океан, если не отчалите от берега», — Христофор Колумб')


class SearchBookView(View):
    def get(self, request):
        query = request.GET.get('s', '')
        if query:
            book = models.Book.objects.filter(title__icontains=query)
        else:
            book = models.Book.objects.none()
        
        return render(
            request,
            'book.html',
            {
                'book': book
            }
        )


class BookDetailView(DetailView):
    model = models.Book
    template_name = 'book_detail.html'
    context_object_name = 'book_id'
    pk_url_kwarg = 'id'


class BookListView(ListView):
    model = models.Book
    template_name = 'book.html'
    context_object_name = 'book'
    paginate_by = 2
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_obj'] = context['paginator'].get_page(self.request.GET.get('page'))
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = context['page_obj']
        return context


class UpdateBookView(UpdateView):
    model = models.Book
    form_class = forms.BookForm
    template_name = 'update_book.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('books:book_user')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_id'] = self.object
        return context


class CreateBookView(CreateView):
    model = models.Book
    form_class = forms.BookForm
    template_name = 'create_book.html'
    success_url = reverse_lazy('books:book_user')


class DeleteBookView(DeleteView):
    model = models.Book
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('books:book_user')
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

templates/book.html
<center>

<button><a href="{% url 'books:create_book' %}">Добавить</a></button>

<br><br>

<form action="{% url 'books:search_book' %}" method="GET">
    <input  type="search" name="s" placeholder="Найти книгу">
    <button type="submit">Найти</button>
</form>

<br><br>

{% for i in book %}

<h1>{{ i.title }}</h1>
<p><a href="{% url 'books:book_detail' i.id %}">Подробнее</a></p>
<p><a href="{% url 'books:delete_book' i.id %}">Удалить</a></p>
<p><a href="{% url 'books:update_book' i.id %}">Редактировать</a></p>

{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if book.has_previous %}
            <a href="?page=1">&laquo; Первая</a>
            <a href="?page={{ book.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ book.number }} из {{ book.paginator.num_pages }}.
        </span>

        {% if book.has_next %}
            <a href="?page={{ book.next_page_number }}">Следующая</a>
            <a href="?page={{ book.paginator.num_pages }}">Последняя &raquo;</a>
        {% endif %}
    </span>
</div>

</center>

 
 

templates/book_detail.html
<center>
<img src="{{ book_id.image.url }}" alt="" width="300" height="300">
<p>{{ book_id.title }}</p>
<p>{{ book_id.description }}</p>
<p>{{ book_id.created_date }}</p>
<p>{{ book_id.creat_at }}</p>
<a href="{{ book_id.viki_lan }}" target="_blank">Перейти на википедию</a>
<br>
<a href="{{ book_id.book_files.url }}" download>Файл книги</a>
</center>
  

templates/categories.html
{% for category in categories %}
<li>
<a href="{% url 'category_products' category.id %}">
{{ category.name }}
</a>
</li>
{% endfor %}

templates/category_products.html
<h1>{{ category.name }}</h1>
{% for product in products %}
<p>{{ product.name }} — {{ product.price }}</p>
{% endfor %}

templates/create_book.html
<center>
<h1>Добавить книгу</h1>
<form action="{% url 'books:create_book' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Добавить</button>
</form>
</center>
 

templates/login.html
<center>
    <h1>Авторизация</h1>

    <form  method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Авторизация</button>

    </form>

    <a href="/register/">Нет аккаунта?</a>

</center>

templates/products.html
{% for product in products %}
<li>
{{ product.name }} —
{{ product.price }} сом —
{{ product.category.name }}
</li>
{% endfor %}

templates/profile.html
<center>
<h2>Здравствуйте {{ request.user.username }}</h2>
</center> 

templates/register.html
<center>
    <h1>Регистрация</h1>

    <form  method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Регистрация</button>


    </form>
</center>

templates/update_book.html
<center>
<h1>Добавить книгу</h1>
 <form  method="post" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Изменить</button>
</form>
</center>